[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://ai-innovate-chatbot.onrender.com/api/:splat"
  status = 200
  force = true

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"